apiVersion: v1
kind: ConfigMap
metadata:
  name: rcj-go-configuration
data:
  config.json: |+
    {
      "appSecretPath":"/secret/credential.json",
      "connectionString":"host=cockroachdb-public port=26257 user=rcjgo dbname=rcj sslmode=disable",
      "ginMode":"development"
    }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rcj-go
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: rcj-go
    spec:
      containers:
      - name: rcj-go
        imagePullPolicy: Always
        image: gcr.io/rcj-containers/rcj-go:master
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
          - name: RCJ_CONFIG_PATH
            value: "/config/config.json"
        volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: cred-volume
            mountPath: /secret
        ports:
          - containerPort: 8080
            name: service
      volumes:
        - name: config-volume
          configMap:
            name: rcj-go-configuration
        - name: cred-volume
          secret:
            secretName: google-sheets-credential
---
apiVersion: v1
kind: Service
metadata:
  name: rcj-go
  labels:
    name: rcj-go
spec:
  type: NodePort
  ports:
    - name: service
      port: 8080
      targetPort: service
  selector:
    app: rcj-go
